### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by leptoid** [LenAnderson/DumbContactSheetMaker#2]
Would like the option of saving output to a custom folder when processing recursive folders.  I like the current method of naming, but this feature would be helpful when adding thumbnails to folders containing zip copies of the folders I am making thumbs of.
Example:
I have a folder containing 400 folders of pictures.  I zip each one with the command line and send them to a folder named "zips".  Now I have a folder with a bunch of files and no previews.  With your software I can generate the previews but I currently have to manually move the previews to the zip folder one at a time or by using a search by date created and hoping I didn't generate any additional content during that time.  
The good side is, you have software that works.  I can't find anything like it.

**Comment by LenAnderson** [comment]
This was bugging me recently as well. I will look into this later this week.

In the meantime I cannot recommend enough [Flexible Renamer](https://hp.vector.co.jp/authors/VA014830/english/FlexRena/) for renaming / moving / copying files and folders based on regular expressions, tags (e.g. ID3, EXIF), and file attributes. Has not received any updates in years and has some issues with the interface (e.g. tabbing through the fields does not work really well) but I have yet to find something equally powerful for Windows.

**Comment by LenAnderson** [comment]
Implemented with release v1.2 (commit 6569a70461f8f2927d4385354b518456ba8a6bdb )
